site_name: Dadaia Tools
repo_url: https://github.com/marcoaureliomenezes/dadaia-tools
repo_name: marcoaureliomenezes/dadaia-tools
edit_uri: tree/main/docs/

theme:
  name: material
  language: pt-BR
  logo: assets/logo.png
  favicon: assets/logo.png

markdown_extensions:
  - attr_list
  - pymdownx.tasklist
  - pymdownx.emoji
  - pymdownx.tilde
  - pymdownx.mark
  - pymdownx.highlight
  - pymdownx.superfences

extra_css:
  - stylesheets/extra.css

plugins:
  - mkdocstrings:
      handlers:
        python:
          paths: [redis_client]

nav:
  - Início: ./index.md
  - Como usar: ./APIs/how_to_use.md
  - Kafka Client: ./APIs/kafka_client.md
  - Redis Client: ./APIs/redis_client.md
  - Kafka Admin: ./APIs/kafka_admin.md