name: Pipeline

on:
    push:
        branches: [develop]
    pull_request:
        branches: [main]


jobs:
    deploy_dadaia_tools:
        runs-on: self-hosted

        steps:
            - name: Git Checkout
              uses: actions/checkout@v2
            

            - name: Install Python
              uses: actions/setup-python@v2
              with:
                  python-version: '3.10'


            - name: Install Poetry
              run: pip install poetry


            - name: Install Package Dependencies
              run: poetry install --without doc


            - name: Install Docker for testing
              uses: docker/setup-buildx-action@v1
       

            - name: Run Package Tests
              env:
                  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
                  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
                  AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
                  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
                  KEY_VAULT_NAME: ${{ secrets.KEY_VAULT_NAME }}
                  STORAGE_ACCOUNT_NAME: ${{ secrets.STORAGE_ACCOUNT_NAME }}
              run: poetry run task test --cov-report=xml


            - name: Upload Test Coverage
              uses: codecov/codecov-action@v3
              with:
                token: ${{ secrets.CODECOV_TOKEN }}


            - uses: actions/checkout@v2
            - uses: everlytic/branch-merge@1.1.2
              with:
                github_token: ${{ github.token }}
                source_ref: develop
                target_branch: 'main'
                commit_message_template: '[Automated] Merged develop into target {target_branch}'


            - name: Build Python Package
              run: poetry build


            - name: Publicação no PyPI
              uses: pypa/gh-action-pypi-publish@release/v1
              with:
                user: ${{ secrets.PYPI_USERS }}
                password: ${{ secrets.PYPI_PASSWORD }}

