name: Pipeline

on: [push]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            
            - name: Install python
              uses: actions/setup-python@v2
              with:
                  python-version: '3.10'

            - name: Install poetry
              run: pip install poetry


            - name: Install dependencies
              run: poetry install --without doc

            - name: Run tests
              run: poetry run task test --cov-report=xml

            - name: Upload coverage
              uses: codecov/codecov-action@v3
              with:
                token: ${{ secrets.CODECOV_TOKEN }}
