name: Pipeline

on:
    push:
        branches: [develop]
    pull_request:
        branches: [main]



jobs:
    test:
        runs-on: self-hosted



        steps:
            - name: Checkout
              uses: actions/checkout@v2
            
            - name: Install python
              uses: actions/setup-python@v2
              with:
                  python-version: '3.10'

            - name: Install poetry
              run: pip install poetry


            - name: Install dependencies
              run: poetry install --without doc

            - name: Install docker
              uses: docker/setup-buildx-action@v1
       
            - name: Run tests
              env:
                  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
                  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
                  AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
                  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
                  KEY_VAULT_NAME: ${{ secrets.KEY_VAULT_NAME }}
                  STORAGE_ACCOUNT_NAME: ${{ secrets.STORAGE_ACCOUNT_NAME }}
              run: poetry run task test --cov-report=xml

            - name: Upload coverage
              uses: codecov/codecov-action@v3
              with:
                token: ${{ secrets.CODECOV_TOKEN }}

            - name: Merge staging -> main
              uses: devmasx/merge-branch@master
              with:
                type: now
                target_branch: main
                github_token: ${{ secrets.GITHUB_TOKEN }}
                